// svelte-client/src/pages/Users.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import UserModal from '../components/UserModal.svelte';
  import ConfirmDialog from '../components/ConfirmDialog.svelte';
  
  // Types
  type User = {
    id: number;
    name: string;
    email: string;
    phone?: string;
  };
  
  // State
  let users: User[] = [];
  let isLoading = true;
  let modalOpen = false;
  let confirmDialogOpen = false;
  let userToEdit: User | null = null;
  let userToDelete: User | null = null;
  let isDeleting = false;
  
  onMount(async () => {
    await fetchUsers();
  });
  
  async function fetchUsers() {
    try {
      isLoading = true;
      const response = await fetch('/api/users');
      const data = await response.json();
      users = data;
    } catch (error) {
      console.error('Error fetching users:', error);
    } finally {
      isLoading = false;
    }
  }
  
  function openAddModal() {
    userToEdit = null;
    modalOpen = true;
  }
  
  function openEditModal(user: User) {
    userToEdit = user;
    modalOpen = true;
  }
  
  function closeModal() {
    modalOpen = false;
  }
  
  function openDeleteDialog(user: User) {
    userToDelete = user;
    confirmDialogOpen = true;
  }
  
  function closeDeleteDialog() {
    confirmDialogOpen = false;
  }
  
  async function handleDeleteUser() {
    if (!userToDelete) return;
    
    isDeleting = true;
    
    try {
      const response = await fetch(`/api/users/${userToDelete.id}`, {
        method: 'DELETE'
      });
      
      if (response.ok) {
        await fetchUsers();
      }
    } catch (error) {
      console.error('Error deleting user:', error);
    } finally {
      isDeleting = false;
      closeDeleteDialog();
    }
  }
  
  async function handleUserSubmit() {
    await fetchUsers();
    closeModal();
  }
</script>

<div>
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-3xl font-bold">Users</h1>
    <button 
      on:click={openAddModal}
      class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
    >
      Add User
    </button>
  </div>
  
  {#if isLoading}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each Array(6) as _}
        <div class="bg-white rounded-lg shadow p-6">
          <div class="animate-pulse">
            <div class="h-5 w-3/4 bg-gray-200 mb-3"></div>
            <div class="h-4 w-1/2 bg-gray-200 mb-2"></div>
            <div class="h-4 w-1/3 bg-gray-200 mb-4"></div>
            <div class="flex justify-end space-x-2">
              <div class="h-8 w-16 bg-gray-200 rounded"></div>
              <div class="h-8 w-16 bg-gray-200 rounded"></div>
            </div>
          </div>
        </div>
      {/each}
    </div>
  {:else if users.length === 0}
    <div class="text-center p-10 bg-white rounded-lg shadow">
      <p class="text-gray-500 mb-4">No users found</p>
      <button 
        on:click={openAddModal}
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
      >
        Add your first user
      </button>
    </div>
  {:else}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each users as user}
        <div class="bg-white rounded-lg shadow overflow-hidden">
          <div class="p-6">
            <h2 class="text-xl font-semibold mb-2">{user.name}</h2>
            <p class="text-sm text-gray-500 mb-1">{user.email}</p>
            {#if user.phone}
              <p class="text-sm text-gray-500 mb-4">{user.phone}</p>
            {:else}
              <p class="text-sm text-gray-400 italic mb-4">No phone number</p>
            {/if}
            
            <div class="flex justify-end space-x-2">
              <button 
                on:click={() => openEditModal(user)}
                class="px-3 py-1 text-sm border border-gray-300 text-gray-700 rounded hover:bg-gray-100"
              >
                Edit
              </button>
              <button 
                on:click={() => openDeleteDialog(user)}
                class="px-3 py-1 text-sm bg-red-600 text-white rounded hover:bg-red-700"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<UserModal 
  isOpen={modalOpen}
  onClose={closeModal}
  userToEdit={userToEdit}
  onSubmit={handleUserSubmit}
/>

<ConfirmDialog
  isOpen={confirmDialogOpen}
  onClose={closeDeleteDialog}
  onConfirm={handleDeleteUser}
  title="Delete User"
  description={`Are you sure you want to delete "${userToDelete?.name}"? This action cannot be undone.`}
  confirmText="Delete"
  cancelText="Cancel"
  isPending={isDeleting}
/>

// temp-backup/src/pages/users.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Plus, Search } from "lucide-react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { queryClient, apiRequest } from "@/lib/queryClient";
import UserModal from "@/components/ui/user-modal";
import ConfirmDialog from "@/components/ui/confirm-dialog";
import UserCard from "@/components/ui/user-card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";

export default function Users() {
  const { toast } = useToast();
  const [searchTerm, setSearchTerm] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [userToEdit, setUserToEdit] = useState<any>(null);
  const [userToDelete, setUserToDelete] = useState<any>(null);

  // Fetch users
  const { data: users, isLoading } = useQuery({
    queryKey: ['/api/users'],
  });

  // Delete user mutation
  const deleteUserMutation = useMutation({
    mutationFn: async (id: number) => {
      const response = await apiRequest('DELETE', `/api/users/${id}`);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/users'] });
      queryClient.invalidateQueries({ queryKey: ['/api/stats'] });
      toast({
        title: "Success",
        description: "User deleted successfully",
      });
      setIsDeleteDialogOpen(false);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Cannot delete user with active rentals",
        variant: "destructive",
      });
      setIsDeleteDialogOpen(false);
    },
  });

  // Handle opening the edit modal
  const handleEditUser = (user: any) => {
    setUserToEdit(user);
    setIsModalOpen(true);
  };

  // Handle opening the create modal
  const handleAddUser = () => {
    setUserToEdit(null);
    setIsModalOpen(true);
  };

  // Handle opening the delete confirmation
  const handleDeleteUser = (user: any) => {
    setUserToDelete(user);
    setIsDeleteDialogOpen(true);
  };

  // Handle confirming deletion
  const confirmDeleteUser = () => {
    if (userToDelete) {
      deleteUserMutation.mutate(userToDelete.id);
    }
  };

  // Filter users based on search term
  const filteredUsers = users
    ? users.filter((user: any) => {
        return user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
               user.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
               (user.phone && user.phone.includes(searchTerm));
      })
    : [];

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
        <div>
          <h2 className="text-2xl font-medium text-neutral-800">Users</h2>
          <p className="text-neutral-500 mt-1">
            Manage user accounts
          </p>
        </div>
        <div className="flex gap-2 mt-2 md:mt-0">
          <Button 
            variant="default" 
            onClick={handleAddUser}
            className="flex items-center gap-1"
          >
            <Plus className="h-4 w-4" />
            <span>Add User</span>
          </Button>
        </div>
      </div>

      {/* Search */}
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-col md:flex-row gap-4 items-center">
            <div className="relative flex-grow">
              <Search className="absolute left-2 top-1/2 transform -translate-y-1/2 text-neutral-400 h-4 w-4" />
              <Input
                placeholder="Search by name, email or phone..."
                className="pl-8"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            
            <Badge variant="outline">
              {users ? users.length : 0} Registered Users
            </Badge>
          </div>
        </CardContent>
      </Card>

      {/* Users grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {isLoading ? (
          // Skeleton loading state
          Array(6).fill(0).map((_, index) => (
            <Card key={index} className="overflow-hidden">
              <div className="p-4 flex items-start">
                <Skeleton className="w-12 h-12 rounded-full" />
                <div className="ml-4 flex-grow">
                  <Skeleton className="h-6 w-3/4 mb-2" />
                  <Skeleton className="h-4 w-full mb-1" />
                  <Skeleton className="h-4 w-1/2" />
                </div>
              </div>
              <div className="p-3 border-t bg-neutral-50 flex justify-end space-x-2">
                <Skeleton className="h-9 w-20" />
                <Skeleton className="h-9 w-20" />
              </div>
            </Card>
          ))
        ) : filteredUsers.length > 0 ? (
          filteredUsers.map((user: any) => (
            <UserCard 
              key={user.id} 
              user={user} 
              onEdit={handleEditUser} 
              onDelete={handleDeleteUser}
            />
          ))
        ) : (
          <div className="col-span-full p-8 text-center text-neutral-500">
            {searchTerm ? 
              "No users match your search criteria" : 
              "No users registered yet"
            }
          </div>
        )}
      </div>

      {/* User Modal */}
      <UserModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)}
        userToEdit={userToEdit}
        onSubmit={() => setIsModalOpen(false)}
      />

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={isDeleteDialogOpen}
        onClose={() => setIsDeleteDialogOpen(false)}
        onConfirm={confirmDeleteUser}
        title="Delete User"
        description={`Are you sure you want to delete "${userToDelete?.name}"? This action cannot be undone.`}
        confirmText="Delete"
        cancelText="Cancel"
        isPending={deleteUserMutation.isPending}
      />
    </div>
  );
}
