// client/src/pages/movies.tsx
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Plus, Search, Filter } from "lucide-react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { queryClient, apiRequest } from "@/lib/queryClient";
import MovieModal from "@/components/ui/movie-modal";
import ConfirmDialog from "@/components/ui/confirm-dialog";
import MovieCard from "@/components/ui/movie-card";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";

export default function Movies() {
  const { toast } = useToast();
  const [searchTerm, setSearchTerm] = useState("");
  const [availableOnly, setAvailableOnly] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [movieToEdit, setMovieToEdit] = useState<any>(null);
  const [movieToDelete, setMovieToDelete] = useState<any>(null);

  // Fetch movies
  const { data: movies, isLoading } = useQuery({
    queryKey: ['/api/movies'],
  });

  // Delete movie mutation
  const deleteMovieMutation = useMutation({
    mutationFn: async (id: number) => {
      const response = await apiRequest('DELETE', `/api/movies/${id}`);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/movies'] });
      queryClient.invalidateQueries({ queryKey: ['/api/stats'] });
      toast({
        title: "Success",
        description: "Movie deleted successfully",
      });
      setIsDeleteDialogOpen(false);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Cannot delete movie with active rentals",
        variant: "destructive",
      });
      setIsDeleteDialogOpen(false);
    },
  });

  // Handle opening the edit modal
  const handleEditMovie = (movie: any) => {
    setMovieToEdit(movie);
    setIsModalOpen(true);
  };

  // Handle opening the create modal
  const handleAddMovie = () => {
    setMovieToEdit(null);
    setIsModalOpen(true);
  };

  // Handle opening the delete confirmation
  const handleDeleteMovie = (movie: any) => {
    setMovieToDelete(movie);
    setIsDeleteDialogOpen(true);
  };

  // Handle confirming deletion
  const confirmDeleteMovie = () => {
    if (movieToDelete) {
      deleteMovieMutation.mutate(movieToDelete.id);
    }
  };

  // Filter movies based on search term and availability filter
  const filteredMovies = movies
    ? movies.filter((movie: any) => {
        const matchesSearch = movie.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                             (movie.director && movie.director.toLowerCase().includes(searchTerm.toLowerCase())) ||
                             (movie.genre && movie.genre.toLowerCase().includes(searchTerm.toLowerCase()));
        
        return matchesSearch && (!availableOnly || movie.available);
      })
    : [];

  // Get count of available movies
  const availableCount = movies ? movies.filter((movie: any) => movie.available).length : 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
        <div>
          <h2 className="text-2xl font-medium text-neutral-800">Movies</h2>
          <p className="text-neutral-500 mt-1">
            Manage your movie library
          </p>
        </div>
        <div className="flex gap-2 mt-2 md:mt-0">
          <Button 
            variant="default" 
            onClick={handleAddMovie}
            className="flex items-center gap-1"
          >
            <Plus className="h-4 w-4" />
            <span>Add Movie</span>
          </Button>
        </div>
      </div>

      {/* Filters and search */}
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="relative flex-grow">
              <Search className="absolute left-2 top-1/2 transform -translate-y-1/2 text-neutral-400 h-4 w-4" />
              <Input
                placeholder="Search by title, director or genre..."
                className="pl-8"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>
            
            <div className="flex items-center gap-4">
              <div className="flex items-center space-x-2">
                <Checkbox 
                  id="available-only" 
                  checked={availableOnly}
                  onCheckedChange={(checked) => setAvailableOnly(checked as boolean)}
                />
                <Label htmlFor="available-only">Available only</Label>
              </div>

              <Badge variant="outline" className="ml-2">
                {movies ? movies.length : 0} Total / {availableCount} Available
              </Badge>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Movies grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {isLoading ? (
          // Skeleton loading state
          Array(6).fill(0).map((_, index) => (
            <Card key={index} className="overflow-hidden">
              <div className="p-4 flex items-start">
                <Skeleton className="w-16 h-20 rounded" />
                <div className="ml-4 flex-grow">
                  <Skeleton className="h-6 w-3/4 mb-2" />
                  <Skeleton className="h-4 w-1/2 mb-4" />
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-full mt-1" />
                </div>
              </div>
              <div className="p-3 border-t bg-neutral-50 flex justify-end space-x-2">
                <Skeleton className="h-9 w-20" />
                <Skeleton className="h-9 w-20" />
              </div>
            </Card>
          ))
        ) : filteredMovies.length > 0 ? (
          filteredMovies.map((movie: any) => (
            <MovieCard 
              key={movie.id} 
              movie={movie} 
              onEdit={handleEditMovie} 
              onDelete={handleDeleteMovie}
            />
          ))
        ) : (
          <div className="col-span-full p-8 text-center text-neutral-500">
            {searchTerm || availableOnly ? 
              "No movies match your search criteria" : 
              "No movies in the library yet"
            }
          </div>
        )}
      </div>

      {/* Movie Modal */}
      <MovieModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)}
        movieToEdit={movieToEdit}
        onSubmit={() => setIsModalOpen(false)}
      />

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={isDeleteDialogOpen}
        onClose={() => setIsDeleteDialogOpen(false)}
        onConfirm={confirmDeleteMovie}
        title="Delete Movie"
        description={`Are you sure you want to delete "${movieToDelete?.title}"? This action cannot be undone.`}
        confirmText="Delete"
        cancelText="Cancel"
        isPending={deleteMovieMutation.isPending}
      />
    </div>
  );
}

// svelte-client/src/pages/Movies.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import MovieModal from '../components/MovieModal.svelte';
  import ConfirmDialog from '../components/ConfirmDialog.svelte';
  
  // Types
  type Movie = {
    id: number;
    title: string;
    director?: string;
    year?: number;
    genre?: string;
    available: boolean;
    description?: string;
  };
  
  // State
  let movies: Movie[] = [];
  let isLoading = true;
  let modalOpen = false;
  let confirmDialogOpen = false;
  let movieToEdit: Movie | null = null;
  let movieToDelete: Movie | null = null;
  let isDeleting = false;
  
  onMount(async () => {
    await fetchMovies();
  });
  
  async function fetchMovies() {
    try {
      isLoading = true;
      const response = await fetch('/api/movies');
      const data = await response.json();
      movies = data;
    } catch (error) {
      console.error('Error fetching movies:', error);
    } finally {
      isLoading = false;
    }
  }
  
  function openAddModal() {
    movieToEdit = null;
    modalOpen = true;
  }
  
  function openEditModal(movie: Movie) {
    movieToEdit = movie;
    modalOpen = true;
  }
  
  function closeModal() {
    modalOpen = false;
  }
  
  function openDeleteDialog(movie: Movie) {
    movieToDelete = movie;
    confirmDialogOpen = true;
  }
  
  function closeDeleteDialog() {
    confirmDialogOpen = false;
  }
  
  async function handleDeleteMovie() {
    if (!movieToDelete) return;
    
    isDeleting = true;
    
    try {
      const response = await fetch(`/api/movies/${movieToDelete.id}`, {
        method: 'DELETE'
      });
      
      if (response.ok) {
        await fetchMovies();
      }
    } catch (error) {
      console.error('Error deleting movie:', error);
    } finally {
      isDeleting = false;
      closeDeleteDialog();
    }
  }
  
  async function handleMovieSubmit() {
    await fetchMovies();
    closeModal();
  }
</script>

<div>
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-3xl font-bold">Movies</h1>
    <button 
      on:click={openAddModal}
      class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
    >
      Add Movie
    </button>
  </div>
  
  {#if isLoading}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each Array(6) as _}
        <div class="bg-white rounded-lg shadow p-6">
          <div class="animate-pulse">
            <div class="h-5 w-3/4 bg-gray-200 mb-3"></div>
            <div class="h-4 w-1/2 bg-gray-200 mb-2"></div>
            <div class="h-4 w-1/3 bg-gray-200 mb-4"></div>
            <div class="h-20 w-full bg-gray-200 rounded mb-4"></div>
            <div class="flex justify-end space-x-2">
              <div class="h-8 w-16 bg-gray-200 rounded"></div>
              <div class="h-8 w-16 bg-gray-200 rounded"></div>
            </div>
          </div>
        </div>
      {/each}
    </div>
  {:else if movies.length === 0}
    <div class="text-center p-10 bg-white rounded-lg shadow">
      <p class="text-gray-500 mb-4">No movies found</p>
      <button 
        on:click={openAddModal}
        class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
      >
        Add your first movie
      </button>
    </div>
  {:else}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {#each movies as movie}
        <div class="bg-white rounded-lg shadow overflow-hidden">
          <div class="p-6">
            <div class="flex justify-between items-start mb-2">
              <h2 class="text-xl font-semibold">{movie.title}</h2>
              <span class={movie.available ? "text-green-600 text-xs font-medium px-2 py-1 bg-green-100 rounded" : "text-red-600 text-xs font-medium px-2 py-1 bg-red-100 rounded"}>
                {movie.available ? 'Available' : 'Not Available'}
              </span>
            </div>
            
            <div class="text-sm text-gray-500 mb-2">
              {#if movie.director || movie.year}
                <p>{movie.director || 'Unknown director'} • {movie.year || 'Unknown year'}</p>
              {/if}
              {#if movie.genre}
                <p class="text-xs text-gray-400">{movie.genre}</p>
              {/if}
            </div>
            
            {#if movie.description}
              <p class="text-sm mb-4">{movie.description}</p>
            {:else}
              <p class="text-sm text-gray-500 italic mb-4">No description available</p>
            {/if}
            
            <div class="flex justify-end space-x-2">
              <button 
                on:click={() => openEditModal(movie)}
                class="px-3 py-1 text-sm border border-gray-300 text-gray-700 rounded hover:bg-gray-100"
              >
                Edit
              </button>
              <button 
                on:click={() => openDeleteDialog(movie)}
                class="px-3 py-1 text-sm bg-red-600 text-white rounded hover:bg-red-700"
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

<MovieModal 
  isOpen={modalOpen}
  onClose={closeModal}
  movieToEdit={movieToEdit}
  onSubmit={handleMovieSubmit}
/>

<ConfirmDialog
  isOpen={confirmDialogOpen}
  onClose={closeDeleteDialog}
  onConfirm={handleDeleteMovie}
  title="Delete Movie"
  description={`Are you sure you want to delete "${movieToDelete?.title}"? This action cannot be undone.`}
  confirmText="Delete"
  cancelText="Cancel"
  isPending={isDeleting}
/>
