// client/src/components/Sidebar.svelte
<script lang="ts">
  import { Home, Film, Users, ShoppingBag } from 'lucide-svelte';
  import { Link, useLocation } from 'svelte-routing';

  export let open = false;
  export let closeSidebar: () => void;

  const navItems = [
    { href: '/', label: 'Dashboard', icon: Home },
    { href: '/movies', label: 'Movies', icon: Film },
    { href: '/users', label: 'Users', icon: Users },
    { href: '/rentals', label: 'Rentals', icon: ShoppingBag }
  ];

  const location = useLocation();
  $: currentPath = $location;
</script>

<aside 
  class="fixed inset-y-0 left-0 z-20 flex flex-col w-64 transition-transform duration-300 ease-in-out transform bg-white border-r border-gray-200 dark:bg-gray-900 dark:border-gray-700 {open ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}"
>
  <div class="p-4 flex justify-between items-center">
    <div class="flex items-center">
      <Film class="h-6 w-6 text-primary" />
      <span class="ml-2 text-lg font-medium text-gray-900 dark:text-white">MovieRent</span>
    </div>
    <button 
      class="p-1 rounded-md text-gray-500 hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-gray-50 dark:hover:bg-gray-800 md:hidden focus:outline-none"
      on:click={closeSidebar}
      aria-label="Close sidebar"
    >
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
      </svg>
    </button>
  </div>

  <nav class="flex-1 px-2 py-4 space-y-1 overflow-y-auto">
    {#each navItems as { href, label, icon }}
      <Link
        to={href}
        class="flex items-center p-3 text-gray-600 dark:text-gray-300 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 {currentPath === href ? 'bg-gray-100 dark:bg-gray-800 text-primary dark:text-primary' : ''}"
        on:click={closeSidebar}
      >
        <svelte:component this={icon} class="h-5 w-5 mr-3 {currentPath === href ? 'text-primary' : ''}" />
        {label}
      </Link>
    {/each}
  </nav>
</aside>

{#if open}
  <div 
    class="fixed inset-0 z-10 bg-gray-900 bg-opacity-50 md:hidden"
    on:click={closeSidebar}
  ></div>
{/if}

// client/src/components/ui/sidebar.tsx
import { useLocation, Link } from "wouter";
import { 
  LayoutDashboard, 
  Film, 
  Users, 
  ClipboardList, 
  Settings, 
  HelpCircle 
} from "lucide-react";

interface SidebarProps {
  open: boolean;
  closeSidebar: () => void;
}

export default function Sidebar({ open, closeSidebar }: SidebarProps) {
  const [location] = useLocation();

  const isActive = (path: string) => {
    return location === path;
  };

  return (
    <>
      {/* Overlay for mobile */}
      {open && (
        <div 
          className="fixed inset-0 bg-black/50 z-10 lg:hidden"
          onClick={closeSidebar}
        ></div>
      )}

      {/* Sidebar */}
      <div 
        className={`w-64 bg-white shadow-md fixed top-0 left-0 h-full pt-14 transform ${
          open ? "translate-x-0" : "-translate-x-full"
        } transition-transform duration-300 lg:transform-none lg:static z-10`}
      >
        <div className="py-4 px-2">
          <div className="p-2 mb-4">
            <div className="text-neutral-700 text-sm font-medium uppercase tracking-wider px-2 mb-2">
              Main Menu
            </div>
            
            <NavItem 
              href="/" 
              label="Dashboard" 
              icon={<LayoutDashboard size={18} />} 
              active={isActive("/")} 
              onClick={closeSidebar}
            />
            
            <NavItem 
              href="/movies" 
              label="Movies" 
              icon={<Film size={18} />} 
              active={isActive("/movies")} 
              onClick={closeSidebar}
            />
            
            <NavItem 
              href="/users" 
              label="Users" 
              icon={<Users size={18} />} 
              active={isActive("/users")} 
              onClick={closeSidebar}
            />
            
            <NavItem 
              href="/rentals" 
              label="Rentals" 
              icon={<ClipboardList size={18} />} 
              active={isActive("/rentals")} 
              onClick={closeSidebar}
            />
          </div>
          
          <div className="p-2">
            <div className="text-neutral-700 text-sm font-medium uppercase tracking-wider px-2 mb-2">
              System
            </div>
            
            <NavItem 
              href="#" 
              label="Settings" 
              icon={<Settings size={18} />} 
              active={false} 
              onClick={closeSidebar}
            />
            
            <NavItem 
              href="#" 
              label="Help" 
              icon={<HelpCircle size={18} />} 
              active={false} 
              onClick={closeSidebar}
            />
          </div>
        </div>
      </div>
    </>
  );
}

interface NavItemProps {
  href: string;
  label: string;
  icon: React.ReactNode;
  active: boolean;
  onClick: () => void;
}

function NavItem({ href, label, icon, active, onClick }: NavItemProps) {
  return (
    <Link href={href}>
      <a 
        className={`flex items-center gap-3 px-2 py-2 rounded-md ${
          active 
            ? "bg-primary/10 text-primary border-l-4 border-primary" 
            : "text-neutral-700 hover:bg-neutral-100 border-l-4 border-transparent"
        } transition-colors`}
        onClick={onClick}
      >
        <span className="text-inherit">{icon}</span>
        <span>{label}</span>
      </a>
    </Link>
  );
}
